version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./php
      args:
        PHP_VERSION: ${PHP_VERSION}
    ports:
      - '8080:80'
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${CODE_ROOT}:/var/www/html
    depends_on:
      - mysql
